import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import enMessages from '../../../messages/en.json'; // Adjust path as necessary
import frMessages from '../../../messages/fr.json'; // Adjust path as necessary
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Harentsoa RANDRIA',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

// Define the messages type
type Messages = {
  en: typeof enMessages;
  fr: typeof frMessages;
};

const messages: Messages = {
  en: enMessages,
  fr: frMessages,
};

export default async function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>) {
  const { locale } = await params; // Await the params

  // Type assertion to ensure locale is a valid key
  const localeKey = locale as keyof Messages;

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages[localeKey]}>
          <div className='flex-grow'>{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
